spring:
  #数据库设置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/littlestar?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: LittleStar
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 321123klklkl
  #清空缓存
  thymeleaf:
    cache: false
  #设置文件上传的大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
#首页路径
server:
  servlet:
    context-path: /




